### ISSUE TITLE
小米pro2安装后重启默认桌面还是多看

### ISSUE THREAD

**Issue by howie6879** [zf3/MiReaderLauncher#1]
@zf3 你好：

小米pro2安装后重启默认桌面还是多看的桌面，没有出现选择默认桌面的提示，请问有解决方案吗。

盼回复。

**Comment by zf3** [comment]
后来解决了是吧，怎么弄的？

**Comment by howie6879** [comment]
解决了，小米pro2多了个设置，在设置里面设置你这个为默认桌面就行

**Comment by zf3** [comment]
OK，我更新下说明。谢谢。
